In [1]:
import numpy as np

In [4]:
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [7]:
data2 = [1,2,3,3.5,4]
data2

[1, 2, 3, 3.5, 4]

In [9]:
# numpy를 이용하여 array 정의하기
# 1. 위에서 만든 python list를 이용

arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [10]:
# array의 형태(크기)를 확인할 수 있다.
arr1.shape

(5,)

In [11]:
# 2. 바로 python list를 넣어 줌으로써 만들기
arr2= np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [13]:
arr2.shape

(5,)

In [15]:
# array의 자료형을 확인할 수 있다.
arr2.dtype

dtype('int32')

In [16]:
arr3 = np.array(data2)
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [17]:
arr3.shape

(5,)

In [18]:
arr3.dtype

dtype('float64')

In [22]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
arr4.shape

(4, 3)

In [26]:
'''
•부호가 있는 정수 int(8, 16, 32, 64)
•부호가 없는 정수 uint(8 ,16, 32, 54)
•실수 float(16, 32, 64, 128)
•복소수 complex(64, 128, 256)
•불리언 bool
•문자열 string_
•파이썬 오프젝트 object
•유니코드 unicode_
'''

SyntaxError: invalid character in identifier (<ipython-input-26-0fd9a9dad8eb>, line 2)

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
# np.zeros() 함수는 인자로 받는 크기만큼, 모든요소가 0인 array를 만든다

In [30]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [32]:
# np.ones() 함수는 인자로 받는 크기만큼, 모든요소가 1인 array를 만든다.

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [36]:
# np.arange() 함수는 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만든다.
# 이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가진다.

In [44]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr1.shape

(2, 3)

In [40]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [41]:
arr2.shape

(2, 3)

In [42]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [43]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [45]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [46]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [48]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [49]:
arr3.shape

(3,)

In [50]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [51]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

In [53]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [54]:
# 요소에 대해 제곱처리
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [55]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# 0번째 요소
arr1[0]

0

In [57]:
# 3번째 요소
arr1[3]

3

In [58]:
# 3번째 요소부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [59]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
# 2차원의 array에서 인덱싱을 하기 위해선 2개의 인자를 입력해야 합니다.
arr2[0,0]

1

In [62]:
# 2행의 모든 요소 꺼내기
arr2[2,:]

array([ 9, 10, 11, 12])

In [64]:
# 2행의 3번째 요소 꺼내기
arr2[2,3]

12

In [65]:
# 모든 열의 3번째 요소 꺼내기
arr2[:,3]

array([ 4,  8, 12])

In [66]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [67]:
names.shape

(8,)

In [85]:
# 아래에서 사용되는 np.random.randn() 함수는 기대값이 0이고, 표준편차가 1인 가우시안 정규 분포를 따르는 난수를 발생시키는 함수이다.
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수도 존재한다.
data = np.random.randn(8,4)
data

array([[ 1.47148624, -0.98741047,  1.05589689, -1.56608302],
       [ 0.11680009,  0.41724976,  0.68153452, -0.25444852],
       [ 1.1708613 , -0.10005086,  0.81675918,  0.44336365],
       [-0.29435487,  0.53487543,  1.037729  , -0.98237335],
       [ 1.15570141, -3.07127583, -1.24000031,  0.31262967],
       [-1.31486134,  0.56171445, -0.70071902, -0.94624887],
       [ 0.72501098,  0.11618765, -0.49477832, -0.23203415],
       [ 1.59553335, -1.14828212, -0.44526708,  1.68416203]])

In [86]:
data.shape

(8, 4)

In [87]:
# 요소가 Beomwoo인 항목에 대한 mask 생성
names_Beomwoo_mask = (names == 'Beomwoo')
names_Beomwoo_mask

array([ True,  True, False, False, False,  True, False,  True])

In [88]:
data[names_Beomwoo_mask,:]

array([[ 1.47148624, -0.98741047,  1.05589689, -1.56608302],
       [ 0.11680009,  0.41724976,  0.68153452, -0.25444852],
       [-1.31486134,  0.56171445, -0.70071902, -0.94624887],
       [ 1.59553335, -1.14828212, -0.44526708,  1.68416203]])

In [89]:
# 요소가 Kim인 행의 데이터만 꺼내기
data[names == 'Kim',:]

array([[ 1.1708613 , -0.10005086,  0.81675918,  0.44336365]])

In [90]:
# 논리 연산을 응용하여, 요소가 Kim 또는 Park인 행의 데이터만 꺼내기
data[(names == 'Kim') | (names == 'Park'),:]

array([[ 1.1708613 , -0.10005086,  0.81675918,  0.44336365],
       [ 0.72501098,  0.11618765, -0.49477832, -0.23203415]])

In [91]:
# 먼저 마스크를 만든다.
# data array에서 0번째 열이 0보다 작은 요소의 boolean 값은 다음과 같다.
data[:,0] < 0

array([False, False, False,  True, False,  True, False, False])

In [92]:
# 위에서 만든 마스크를 이용하여 0번째 열의 값이 0보다 작은 행을 구한다.
data[data[:,0]<0,:]

array([[-0.29435487,  0.53487543,  1.037729  , -0.98237335],
       [-1.31486134,  0.56171445, -0.70071902, -0.94624887]])

In [94]:
# 0번째 열의 값이 0보다 작은 행의 2,3번째 열 값
data[data[:,0]<0,2:4]

array([[ 1.037729  , -0.98237335],
       [-0.70071902, -0.94624887]])

In [95]:
data[data[:,0]<0,2:4] = 0
data

array([[ 1.47148624, -0.98741047,  1.05589689, -1.56608302],
       [ 0.11680009,  0.41724976,  0.68153452, -0.25444852],
       [ 1.1708613 , -0.10005086,  0.81675918,  0.44336365],
       [-0.29435487,  0.53487543,  0.        ,  0.        ],
       [ 1.15570141, -3.07127583, -1.24000031,  0.31262967],
       [-1.31486134,  0.56171445,  0.        ,  0.        ],
       [ 0.72501098,  0.11618765, -0.49477832, -0.23203415],
       [ 1.59553335, -1.14828212, -0.44526708,  1.68416203]])

In [96]:
arr1 = np.random.randn(5,3)
arr1

array([[-0.99387403,  2.40836106, -0.38443005],
       [ 1.99497767, -0.20338486,  0.55873325],
       [-0.56636276,  2.28703955,  0.57433639],
       [ 1.01308759,  2.02135937, -0.95160396],
       [-1.07645652, -1.61149646,  1.40448925]])

In [97]:
# 각 성분의 절대값 계산하기
np.abs(arr1)

array([[0.99387403, 2.40836106, 0.38443005],
       [1.99497767, 0.20338486, 0.55873325],
       [0.56636276, 2.28703955, 0.57433639],
       [1.01308759, 2.02135937, 0.95160396],
       [1.07645652, 1.61149646, 1.40448925]])

In [98]:
# 각 성분의 제곱근 계산하기 ( == array ** 0.5)
np.sqrt(arr1)

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([[       nan, 1.55188951,        nan],
       [1.41243678,        nan, 0.74748462],
       [       nan, 1.51229612, 0.75784985],
       [1.00652252, 1.42174518,        nan],
       [       nan,        nan, 1.18511149]])

In [99]:
2:4

SyntaxError: illegal target for annotation (<ipython-input-99-9857ad00e288>, line 1)